#!/bin/bash

sudo apt install nginx
sudo add-apt-repository ppa:certbot/certbot
sudo apt install python-certbot-nginx

# Configure Nginx
mkdir -p /etc/nginx/sites-available/
mkdir -p /etc/nginx/sites-enabled/
sudo cp configs/nginx /etc/nginx/sites-available/homebackend
sudo ln -s /etc/nginx/sites-available/homebackend /etc/nginx/sites-enabled/

# Configure backend service
sudo cp configs/system.service /etc/systemd/system/homebackend.service

# Restart system services
sudo systemctl daemon-reload
sudo systemctl restart nginx
sudo systemctl start homebackend
sudo systemctl enable homebackend

# Setup firewall
sudo ufw allow http
sudo ufw allow https
sudo ufw allow ssh
sudo ufw allow 8000


# Sign https certificate
sudo certbot --nginx -d api.weitungchen.com -d api.weitungchen.com

