#!/bin/bash

sudo apt install nginx
sudo add-apt-repository ppa:certbot/certbot
sudo apt install python3-certbot-nginx

# Configure Nginx
mkdir -p /etc/nginx/sites-available/
mkdir -p /etc/nginx/sites-enabled/
sudo cp configs/nginx /etc/nginx/sites-available/homebackend
sudo ln -s /etc/nginx/sites-available/homebackend /etc/nginx/sites-enabled/

# Configure backend service
sudo cp configs/system.service /etc/systemd/system/homebackend.service

# Install certbot config manually
wget https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
mv options-ssl-nginx.conf /etc/letsencrypt/

# Restart system services
sudo systemctl daemon-reload
sudo systemctl restart nginx
sudo systemctl start homebackend
sudo systemctl enable homebackend

# Setup firewall
sudo ufw allow http
sudo ufw allow https
sudo ufw allow ssh
sudo ufw allow 8000


# Sign https certificate
sudo certbot --nginx -d api.chessvibe.net -d api.chessvibe.net

